Created Links for Extension slot of Add Patient Button on Primary navbar
openmrs/openmrs-esm-patient-registration pull request #74
Opened 2021-03-09 06:22 UTC by ujjwaltyagi355

Hi, @FlorianRappl,
I have created these links for the extension slot for Add Patient button on the Primary Navbar.
For the issue [MF-464](https://issues.openmrs.org/browse/MF-464).
Do have a look and tell me if any changes are needed to be made.

2021-03-09 07:10 UTC, ujjwaltyagi355 commented
Hello, @FlorianRappl, 
I am unsure of what is causing the build failure.
Can you have a look?
Thank you.

2021-03-09 08:24 UTC, FlorianRappl commented
Hi @ujjwaltyagi355 there is a type error:

> Error: src/index.ts(48,40): error TS2322: Type 'string' is not assignable to type 'Promise<{ default: ComponentType<unknown>; }>'.

Please correct the type.

In short, instead of getting the module loaded asynchronously, you just return the name of the module...

```js
        load : getAsyncLifecycle(() => ('./add-patient-link'),options),
```

should be

```js
        load : getAsyncLifecycle(() => import('./add-patient-link'),options),
```

Also please use [prettier](https://prettier.io/). Obviously, this code was not prettified. Thanks!

2021-03-09 08:35 UTC, ujjwaltyagi355 commented
@FlorianRappl,
Thanx for pointing that out.
Such a silly mistake I just made.

2021-03-09 11:41 UTC, ujjwaltyagi355 commented
Hello, @FlorianRappl,
Is this good?

2021-03-09 19:10 UTC, FlorianRappl requested changes

2021-03-09 19:10 UTC, FlorianRappl commented on src/add-patient-link.tsx
> +    <ConfigurableLink to="${openmrsSpaBase}/patient-registration">
Should be wrapped in a `HeaderGlobalAction` with props:

```
aria-label="Add"
aria-labelledby="Add Patient"
name="AddPatientIcon"
```

2021-03-09 19:10 UTC, FlorianRappl commented on src/index.ts
> +        id: 'add-patient-primary-nav',
add-patient-action

2021-03-09 19:10 UTC, FlorianRappl commented on src/index.ts
> +        slot : 'add-patient-slot',
top-nav-actions-slot

2021-03-10 10:01 UTC, FlorianRappl commented on src/add-patient-link.tsx
> +import { Add20 } from '@carbon/icons-react';
Use the explicit module import, should be something like `@carbon/icons-react/es/components/add/20` or so

2021-03-10 12:02 UTC, FlorianRappl approved these changes
Great! :beers:

2021-03-10 12:02 UTC, merged